### ISSUE TITLE
Bug in sig_mahal_knn.py

### ISSUE THREAD

**Issue by sz85512678** [datasig-ac-uk/signature_mahalanobis_knn#12]
In line 109-124:
            # set default kwargs for signature transformer if not provided
            if signature_kwargs is None or signature_kwargs == {}:
                signature_kwargs = {
                    "augmentation_list": ("addtime",),
                    "window_name": "global",
                    "window_depth": None,
                    "window_length": None,
                    "window_step": None,
                    "rescaling": None,
                    "sig_tfm": "signature",
                    "depth": 2,
                }

            self.signature_transform = SignatureTransformer(
                **signature_kwargs,
            )

If the user input signature_kwargs = {"depth": 3}, the above code will set the other argument of the SignatureTransformer as its default, which has default augmentation_list as augmentation_list=('basepoint', 'addtime'); This produces different results.

A hack would be to explicitly provide all the signature_kwargs but this is a potential source for future errors. However even with this fixed the distance computed is still an order of magnitude larger than the previous methods, suggesting some further bugs somewhere. We need to make sure the distances are the same. 

For example, running depth 4, digit 0 gives an instance of inlier_dists: 
array([0.10293763, 0.21655908, 0.17555342, 0.37821957, 2.52220155,
       0.25794536, 0.19356175, 1.8735614 , 0.21667799, 0.21799781,
       0.30084204, 0.14079295, 0.19137239, 1.0841934 , 0.20703369,
       1.16883841, 0.25666209, 4.09705851, 0.28626317, 2.27759731,
       0.17592573, 0.40444251, 0.22031607, 0.152825  , 0.13235025,
       0.12575332, 0.14180312, 0.65683611, 0.78451488, 0.23221037])

But for the previous method, the dists are"
array([[0.00048547],
       [0.00069512],
       [0.00026231],
       [0.00024205],
       [0.01478617],
       [0.00101271],
       [0.00063996],
       [0.01085489],
       [0.00031296],
       [0.0003389 ],
       [0.0009286 ],
       [0.0001704 ],
       [0.00065423],
       [0.0053868 ],
       [0.00033216],
       [0.00559567],
       [0.00057974],
       [0.03442473],
       [0.00139299],
       [0.01456522],
       [0.00034281],
       [0.00019561],
       [0.00018355],
       [0.00015556],
       [0.0005628 ],
       [0.00013005],
       [0.00049769],
       [0.00200352],
       [0.00387577],
       [0.00061396]])

**Comment by sz85512678** [comment]
Further comment, as we are now actively trying to develop new functionalities, we should write unit tests, for example, to ensure those distances are the same.

**Comment by rchan26** [comment]
Think fixed now in `transform-euclidean` and `paper-example` branches

**Comment by rchan26** [comment]
Doesn't exactly reproduce the results, but gets high ROCAUC.
